// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuwF--VW5hVDSTPVRv0gz4ZLm51HJFBvE',
    appId: '1:933638951264:android:9e779fc3c959baf39c0e05',
    messagingSenderId: '933638951264',
    projectId: 'eight-night',
    storageBucket: 'eight-night.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3xznGGhzAdYCMqt9xxKkT_jUGTFRmnR8',
    appId: '1:933638951264:ios:bc04ed4b1cb7e8409c0e05',
    messagingSenderId: '933638951264',
    projectId: 'eight-night',
    storageBucket: 'eight-night.appspot.com',
    androidClientId: '933638951264-vs4go1aceu3ukgorc14ggcus39pk2a8q.apps.googleusercontent.com',
    iosClientId: '933638951264-v65mmp0pdd9pnh00ua7q8i4qm7rm68n3.apps.googleusercontent.com',
    iosBundleId: 'com.example.eightNight',
  );
}
